name: CI

on:
  push:
    branches: 
      - master # add more branches as necessary
    tags: "*"
  pull_request:

jobs:
  Documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --project=docs/ docs/make.jl

  Testing:
      name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          julia-version:
            - 1
            - nightly # test on Latest and nightly
          arch: 
            - x64 # only test 64 bit
          os: 
            - ubuntu-latest
            - windows-latest # add mac test if needed
          
      steps:
        - uses: actions/checkout@v2
        - uses: julia-actions/setup-julia@v1
          with:
            version: ${{ matrix.version }}
            arch: ${{ matrix.arch }}
        - uses: actions/cache@v1
          env:
            cache-name: cache-artifacts
          with:
            path: ~/.julia/artifacts
            key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
            restore-keys: |
              ${{ runner.os }}-test-${{ env.cache-name }}-
              ${{ runner.os }}-test-
              ${{ runner.os }}-
        - uses: julia-actions/julia-buildpkg@latest
        - run: |
            git config --global user.name Tester
            git config --global user.email te@st.er
        - uses: julia-actions/julia-runtest@latest
        - uses: julia-actions/julia-processcoverage@v1
        - uses: codecov/codecov-action@v1
          with:
            file: lcov.info